server:
  session-timeout: 600

management:
  add-application-context-header: false
  security:
    enabled: false

endpoints:
  shutdown:
    enabled: true

spring:
  freemarker:
    charset: UTF-8

security:
  basic:
    enabled: false

build:
  number: 2